monolog:
    handlers:
        applog:
            type: stream
            path: /tmp/mono.log
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
